# Generated by Django 5.2.14

from django.db import migrations, models


def backfill_transaction_currencies(apps, schema_editor):
    Transaction = apps.get_model("financetracker", "Transaction")
    Transaction.objects.all().update(currency="CZK")


class Migration(migrations.Migration):

    dependencies = [
        ("financetracker", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(default="CZK", max_length=3),
        ),
        migrations.RunPython(backfill_transaction_currencies, migrations.RunPython.noop),
    ]
