# Generated by Django 5.2.14 on 2026-07-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financetracker', '0005_transaction_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_successful_sync_date', models.DateField(blank=True, null=True)),
                ('supported_currencies', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('rate_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['rate_date', 'quote_currency'], name='financetrac_rate_da_1378c0_idx')],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'rate_date'), name='unique_exchange_rate')],
            },
        ),
    ]
