# Generated by Django 5.2.14 on 2026-07-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financetracker', '0007_syncmetadata_sync_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('warm', 'Warm Ledger'), ('night', 'Night Ledger'), ('system', 'System')], default='system', max_length=16),
        ),
    ]
