# Generated by Django 5.2.14 on 2026-07-18 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financetracker', '0008_userprofile_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IOU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('receivable', 'Receivable'), ('payable', 'Payable')], max_length=10)),
                ('counterparty_name', models.CharField(max_length=255)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='CZK', max_length=3)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opening_iou', to='financetracker.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ious', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IOU',
                'ordering': ['-created_at'],
            },
        ),
    ]
