# Generated by Django 5.2.14 on 2026-07-18 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financetracker', '0009_add_iou_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOURepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='financetracker.iou')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='iou_repayment', to='financetracker.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
