# Generated by Django 5.2.14 on 2026-07-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financetracker', '0010_add_iou_repayment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('warm', 'Warm Ledger'), ('night', 'Night Ledger'), ('cool', 'Cool Ledger'), ('system', 'System')], default='system', max_length=16),
        ),
    ]
