# Generated by Django 5.2.14 on 2026-07-25 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

DEFAULT_CASH_CURRENCY = "CZK"
CASH_BANK_ACCOUNT_NAME = "Cash"


def backfill_cash_bank_accounts(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("financetracker", "UserProfile")
    BankAccount = apps.get_model("financetracker", "BankAccount")
    Transaction = apps.get_model("financetracker", "Transaction")

    for user in User.objects.all():
        profile = UserProfile.objects.filter(user_id=user.id).first()
        currency = profile.default_currency if profile is not None else DEFAULT_CASH_CURRENCY
        cash, _created = BankAccount.objects.get_or_create(
            user_id=user.id,
            is_cash=True,
            defaults={
                "name": CASH_BANK_ACCOUNT_NAME,
                "currency": currency,
                "kind": "",
            },
        )
        Transaction.objects.filter(user_id=user.id, bank_account_id__isnull=True).update(
            bank_account_id=cash.id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("financetracker", "0011_userprofile_theme_cool_ledger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("currency", models.CharField(max_length=3)),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("checking", "Checking"),
                            ("savings", "Savings"),
                            ("credit", "Credit"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("is_cash", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_cash", "name"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="financetracker.bankaccount",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_cash", True)),
                fields=("user",),
                name="unique_cash_bank_account_per_user",
            ),
        ),
        migrations.RunPython(backfill_cash_bank_accounts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="transaction",
            name="bank_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="financetracker.bankaccount",
            ),
        ),
    ]
