# Generated by Django 5.2.14 on 2026-07-25 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financetracker', '0012_bank_account_and_transaction_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='opening_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_for_bank_account', to='financetracker.transaction'),
        ),
    ]
