# Generated by Django 5.2.14 on 2026-07-25 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financetracker', '0013_bank_account_opening_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_destination_for', to='financetracker.transaction')),
                ('from_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='financetracker.bankaccount')),
                ('source_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_source_for', to='financetracker.transaction')),
                ('to_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='financetracker.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
